### ISSUE TITLE
mp7 failed to run; forrtl: severe (111): position number is outside of the valid range, unit 116

### ISSUE THREAD

**Issue by SvenVanZoggel** [MODFLOW-USGS/modpath-v7#40]
Dear modpath experts,

I am a student currently working with flopy and I have come across the following error when running mp7:

![afbeelding](https://github.com/MODFLOW-USGS/modpath-v7/assets/136890083/0ece42ea-4f23-46a8-a71d-faf4472ba9c7)

I have a model that starts with a steady state stress period and it is followed by multiple transient periods in which I only change the extraction rates of the well. Each transient stress period is 180 days and I want to release particles over multiple years. When I release 60 particle sets with a release interval of 36 days everything is working fine. But I would like to release particle sets more often and reduce the release interval more. I tried to release 540 particle sets with a release time interval of 4 days, 270 sets every 8 days and 120 sets every 18 days but they all end in the same error of the image I sent. The particles are released from the bottom of a river.
So, my question is if you ever came across this error and if you know what this error really means?
I hope you can help me, I look forward to your reply.

Kind regards,
Sven van Zoggel

**Comment by wpbonelli** [comment]
@SvenVanZoggel it is hard to say why this might happen without reproducing it (maybe your output is just too large?) but I can say where: while tracking particles, mp7 writes them to temporary binary files &mdash; when complete it consolidates these into the familiar output files. It looks like this file access error (which I believe is specific to intel fortran) is raised while reading the temporary file.

You might try MODFLOW 6 which recently got new particle tracking capabilities. It writes directly to CSV or binary output files as it goes instead of keeping an internal buffer in memory or on disk, so it may not end up in this situation like mp7 does. An example of migrating an mp7 model to MF6 PRT can be found [here](https://modflow6-examples.readthedocs.io/en/latest/_notebooks/ex-prt-mp7-p03.html). Note you'll need MF6.5.0 which is just a few days old

**Comment by aprovost-usgs** [comment]
@SvenVanZoggel As @wpbonelli suggested, this has to do with the process of consolidating output and is almost certainly related to issue #21.  The limit you've likely been running into has been increased in the updated, provisional code on the develop branch of this repo (in "msvs/bin_PROVISIONAL").

**Comment by wkitlasten** [comment]
I’m not sure I fully understand your setup, but perhaps you could do all
your particle releases as separate MODPATH simulations? In my models I am
running MODFLOW once, then using the results to run about 100 separate
MODPATH simulations each with 10,000+ particles each. I am also using the
provisional code @aprovost mentioned.

"Perfect spheres are pointless."

**Comment by SvenVanZoggel** [comment]
Thanks for your fast responses, if I still have time left I will try to produce separate MODPATH simulations, thanks for now!

**Comment by kbefus** [comment]
I would like to confirm that @aprovost-usgs's suggestion that it was related to #21 and that the provisional executable fixed this error for me without having to break up a large particle tracking simulation based on a transient 3D MODFLOW 6 model. The error occurred after the full particle tracking simulation and as the pathlines were being compiled (very beginning of the pth loading in the mp7.log file).

**Comment by aprovost-usgs** [comment]
@kbefus, thank you for the confirmation.
